/*#EESE_PUSH_CI/*/

pipeline{
	agent any
	
	stages {
		stage ('Version/Release Notes') {
			steps {
				sh "la -l; pwd"
				sh "../steps/ReleaseNotesVersion.sh" 
			}
		}
            
		stage ('Merge source branch') {
			steps {
				sh "../steps/Merge.sh"
			}
		}
		
		stage ('Static Checks') {
				steps {
					sh "../steps/StatiChecks.sh"
				}
		}
		
		stage ('Build'){
				steps {
					sh "../steps/Build.sh"
				}
		}
		
		stage ('Unit Test') {
				steps {
					sh "../steps/unitTest.sh"
				}
		}
	}
}
