/*#EESE_PUSH_CI/*/

pipeline{
	agent any
	
	stages {
		stage ('Version/Release Notes') {
			steps {
				sh "echo 'Get Version and Release notes'"
			}
		}
            
		stage ('Merge source branch') {
			steps {
				sh "echo 'task to merge the branch'"
			}
		}
		
		stage ('Static Checks') {
				steps {
					sh "echo 'Tasks for static checks'"
				}
		}
		
		stage ('Build'){
				steps {
					sh "echo 'Task to build'"
				}
		}
		
		stage ('Unit Test') {
				steps {
					sh "echo 'Task to do Unit Test'"
				}
		}
	}
}
